### PR TITLE
upgrading pip seems dangerous now

### PR DESCRIPTION
**Pull request by mhsieh**
don't merge yet

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Oh, because you're using an older version of **virtualenv** that actually works on Centos7?

**Comment by mhsieh** [comment]
I still have problem on freetype snafu, (i.e. matplotlib), but how do I test the virtualenv issue you mentioned?

**Comment by pb-cdunn** [comment]
Simply login to one of our Centos7 nodes, clone `pypa/virtualenv`, and try to run it. You're using an old version of **virtualenv** for a reason, right?

**Comment by mhsieh** [comment]
I was using an older version of virtualenv because I was burned following the trunk version before.

**Comment by mhsieh** [comment]
Also got burned by pip upgrade last year, it requires time to heal the scars.

**Pull request merged**
