### PR TITLE
Update

### PR DESCRIPTION
**Pull request by pb-cdunn**
You could drop rdflib/rdfextras/html5lib now, if you want.

### CODE REVIEW

**Comment by mhsieh** [comment]
nice

**Comment by pb-cdunn** [comment]
```

**Comment by pb-cdunn** [comment]
```sh
cd /home/travis/workspace/bam2fastx && git submodule update --init -- third-party/cpp-optparse
error: pathspec 'third-party/cpp-optparse' did not match any file(s) known to git.
```

**Comment by mhsieh** [comment]
the fix is in the master, how do I re-trigger the merge

**Comment by mhsieh** [comment]
Or we can close this pr and redo the pr again.

**Comment by pb-cdunn** [comment]
Since the branch is in *this* repo, you have access to it. You can simply rebase locally and then `git push -f origin update:update`. I'll do that now...

**Comment by pb-cdunn** [comment]
```

**Pull request merged**
