### PR TITLE
Initialize separately

### PR DESCRIPTION
**Pull request by pb-cdunn**
make init
    make -j world

There are still other problems with multi-job builds, but this gets us closer.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
```

**Comment by pb-cdunn** [comment]
Locally, I get this:
```

**Comment by pb-cdunn** [comment]
SWIG_COMMAND=$(shell . $(PREFIX)/setup-env.sh && which swig)

I see. I missed `setup-env.sh` in `init.mk`.... Done.

**Comment by pb-cdunn** [comment]
In building **swig**:
```
checking string presence... no
configure: WARNING: string: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: string: proceeding with the compiler's result
```
The `configure` scripts checks for `<string.h>`, while using `g++`. Since it's not found, it assumes that C++ is not possible, so it does not fully build pcrecpp files. (I think that version would require `#include <cstring>`, the new header name.) At least, that's what I gather from googling. I see `pcrecpp.o`, so I'm not completely sure....

... It builds fine with `gcc-4.8.2`, but not with `gcc-4.9.2`. We need an updated tarball, I guess.... Hmmm, well, there is no later version. Only a major-major change to **pcre2**.
* ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/

**Comment by mjhsieh** [comment]
I don't understand the need to have SWIG_COMMAND when swig is in PREFIX/bin already. Unless `export PATH` is not enough.

**Comment by mhsieh** [comment]
`checking string presence... no` doesn't look right to me. What's the login host you were using?

**Comment by pb-cdunn** [comment]
Well, it is working now. I think the change was `module unload gcc; export CPATH=`./mnt/software/g/gcc/4.9.2/libc-2.5`. But I'll try `make world` on another machine soon --- after I try a multi-job build on the login node. (It's a weekend, right?) Multi-job is high priority because it makes iterations faster. And I want `make -j pbbam`, and a few other slow ones.

**Comment by mhsieh** [comment]
Yes. Let's make this a higher priority.

**Pull request merged**
